# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Basys3_Master.xdc

# Block Designs: bd/exp1/exp1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp1 || ORIG_REF_NAME==exp1} -quiet] -quiet

# IP: bd/exp1/ip/exp1_vio_1_1/exp1_vio_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp1_vio_1_1 || ORIG_REF_NAME==exp1_vio_1_1} -quiet] -quiet

# IP: bd/exp1/ip/exp1_display_interface_0_1/exp1_display_interface_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==exp1_display_interface_0_1 || ORIG_REF_NAME==exp1_display_interface_0_1} -quiet] -quiet

# XDC: bd/exp1/exp1_ooc.xdc
